[book]
authors = ["Stefan Hagen"]
language = "en"
multilingual = false
src = "."
title = "Gengive"

[preprocessor.embed]

[build]
builddir = "book"

[output.html]
mathjax-support = true
site-url = "/docs/gengive"
git-repository-url = "https://git.sr.ht/~sthagen/gengive"

